<?php
/**
 * TenantApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Probatix API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * TenantApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TenantApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiTenantsGetItem' => [
            'application/json',
        ],
        'apiTenantsPutItem' => [
            'application/json',
            'application/ld+json',
        ],
        'xXDeprecatedApiTenantsGetItem' => [
            'application/json',
        ],
        'xXDeprecatedApiTenantsPutItem' => [
            'application/json',
            'application/ld+json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiTenantsGetItem
     *
     * Retrieves a Tenant resource.
     *
     * @param  string $uuid Tenant identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiTenantsGetItem'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\TenantTenantRead
     */
    public function apiTenantsGetItem($uuid, string $contentType = self::contentTypes['apiTenantsGetItem'][0])
    {
        list($response) = $this->apiTenantsGetItemWithHttpInfo($uuid, $contentType);
        return $response;
    }

    /**
     * Operation apiTenantsGetItemWithHttpInfo
     *
     * Retrieves a Tenant resource.
     *
     * @param  string $uuid Tenant identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiTenantsGetItem'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\TenantTenantRead, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiTenantsGetItemWithHttpInfo($uuid, string $contentType = self::contentTypes['apiTenantsGetItem'][0])
    {
        $request = $this->apiTenantsGetItemRequest($uuid, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\TenantTenantRead' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\TenantTenantRead' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\TenantTenantRead', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\TenantTenantRead';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\TenantTenantRead',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiTenantsGetItemAsync
     *
     * Retrieves a Tenant resource.
     *
     * @param  string $uuid Tenant identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiTenantsGetItem'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiTenantsGetItemAsync($uuid, string $contentType = self::contentTypes['apiTenantsGetItem'][0])
    {
        return $this->apiTenantsGetItemAsyncWithHttpInfo($uuid, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiTenantsGetItemAsyncWithHttpInfo
     *
     * Retrieves a Tenant resource.
     *
     * @param  string $uuid Tenant identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiTenantsGetItem'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiTenantsGetItemAsyncWithHttpInfo($uuid, string $contentType = self::contentTypes['apiTenantsGetItem'][0])
    {
        $returnType = '\OpenAPI\Client\Model\TenantTenantRead';
        $request = $this->apiTenantsGetItemRequest($uuid, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiTenantsGetItem'
     *
     * @param  string $uuid Tenant identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiTenantsGetItem'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiTenantsGetItemRequest($uuid, string $contentType = self::contentTypes['apiTenantsGetItem'][0])
    {

        // verify the required parameter 'uuid' is set
        if ($uuid === null || (is_array($uuid) && count($uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uuid when calling apiTenantsGetItem'
            );
        }


        $resourcePath = '/api/v2/instance/tenants/{uuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'uuid' . '}',
                ObjectSerializer::toPathValue($uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/ld+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-AUTH-TOKEN');
        if ($apiKey !== null) {
            $headers['X-AUTH-TOKEN'] = $apiKey;
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiTenantsPutItem
     *
     * Replaces the Tenant resource.
     *
     * @param  string $uuid Tenant identifier (required)
     * @param  \OpenAPI\Client\Model\TenantTenantWrite $tenant_tenant_write The updated Tenant resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiTenantsPutItem'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\TenantTenantRead
     */
    public function apiTenantsPutItem($uuid, $tenant_tenant_write, string $contentType = self::contentTypes['apiTenantsPutItem'][0])
    {
        list($response) = $this->apiTenantsPutItemWithHttpInfo($uuid, $tenant_tenant_write, $contentType);
        return $response;
    }

    /**
     * Operation apiTenantsPutItemWithHttpInfo
     *
     * Replaces the Tenant resource.
     *
     * @param  string $uuid Tenant identifier (required)
     * @param  \OpenAPI\Client\Model\TenantTenantWrite $tenant_tenant_write The updated Tenant resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiTenantsPutItem'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\TenantTenantRead, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiTenantsPutItemWithHttpInfo($uuid, $tenant_tenant_write, string $contentType = self::contentTypes['apiTenantsPutItem'][0])
    {
        $request = $this->apiTenantsPutItemRequest($uuid, $tenant_tenant_write, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\TenantTenantRead' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\TenantTenantRead' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\TenantTenantRead', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\TenantTenantRead';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\TenantTenantRead',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiTenantsPutItemAsync
     *
     * Replaces the Tenant resource.
     *
     * @param  string $uuid Tenant identifier (required)
     * @param  \OpenAPI\Client\Model\TenantTenantWrite $tenant_tenant_write The updated Tenant resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiTenantsPutItem'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiTenantsPutItemAsync($uuid, $tenant_tenant_write, string $contentType = self::contentTypes['apiTenantsPutItem'][0])
    {
        return $this->apiTenantsPutItemAsyncWithHttpInfo($uuid, $tenant_tenant_write, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiTenantsPutItemAsyncWithHttpInfo
     *
     * Replaces the Tenant resource.
     *
     * @param  string $uuid Tenant identifier (required)
     * @param  \OpenAPI\Client\Model\TenantTenantWrite $tenant_tenant_write The updated Tenant resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiTenantsPutItem'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiTenantsPutItemAsyncWithHttpInfo($uuid, $tenant_tenant_write, string $contentType = self::contentTypes['apiTenantsPutItem'][0])
    {
        $returnType = '\OpenAPI\Client\Model\TenantTenantRead';
        $request = $this->apiTenantsPutItemRequest($uuid, $tenant_tenant_write, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiTenantsPutItem'
     *
     * @param  string $uuid Tenant identifier (required)
     * @param  \OpenAPI\Client\Model\TenantTenantWrite $tenant_tenant_write The updated Tenant resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiTenantsPutItem'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiTenantsPutItemRequest($uuid, $tenant_tenant_write, string $contentType = self::contentTypes['apiTenantsPutItem'][0])
    {

        // verify the required parameter 'uuid' is set
        if ($uuid === null || (is_array($uuid) && count($uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uuid when calling apiTenantsPutItem'
            );
        }

        // verify the required parameter 'tenant_tenant_write' is set
        if ($tenant_tenant_write === null || (is_array($tenant_tenant_write) && count($tenant_tenant_write) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant_tenant_write when calling apiTenantsPutItem'
            );
        }


        $resourcePath = '/api/v2/instance/tenants/{uuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'uuid' . '}',
                ObjectSerializer::toPathValue($uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/ld+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($tenant_tenant_write)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($tenant_tenant_write));
            } else {
                $httpBody = $tenant_tenant_write;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-AUTH-TOKEN');
        if ($apiKey !== null) {
            $headers['X-AUTH-TOKEN'] = $apiKey;
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation xXDeprecatedApiTenantsGetItem
     *
     * Retrieves a Tenant resource.
     *
     * @param  string $uuid Tenant identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['xXDeprecatedApiTenantsGetItem'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\TenantTenantRead
     * @deprecated
     */
    public function xXDeprecatedApiTenantsGetItem($uuid, string $contentType = self::contentTypes['xXDeprecatedApiTenantsGetItem'][0])
    {
        list($response) = $this->xXDeprecatedApiTenantsGetItemWithHttpInfo($uuid, $contentType);
        return $response;
    }

    /**
     * Operation xXDeprecatedApiTenantsGetItemWithHttpInfo
     *
     * Retrieves a Tenant resource.
     *
     * @param  string $uuid Tenant identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['xXDeprecatedApiTenantsGetItem'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\TenantTenantRead, HTTP status code, HTTP response headers (array of strings)
     * @deprecated
     */
    public function xXDeprecatedApiTenantsGetItemWithHttpInfo($uuid, string $contentType = self::contentTypes['xXDeprecatedApiTenantsGetItem'][0])
    {
        $request = $this->xXDeprecatedApiTenantsGetItemRequest($uuid, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\TenantTenantRead' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\TenantTenantRead' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\TenantTenantRead', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\TenantTenantRead';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\TenantTenantRead',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation xXDeprecatedApiTenantsGetItemAsync
     *
     * Retrieves a Tenant resource.
     *
     * @param  string $uuid Tenant identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['xXDeprecatedApiTenantsGetItem'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function xXDeprecatedApiTenantsGetItemAsync($uuid, string $contentType = self::contentTypes['xXDeprecatedApiTenantsGetItem'][0])
    {
        return $this->xXDeprecatedApiTenantsGetItemAsyncWithHttpInfo($uuid, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation xXDeprecatedApiTenantsGetItemAsyncWithHttpInfo
     *
     * Retrieves a Tenant resource.
     *
     * @param  string $uuid Tenant identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['xXDeprecatedApiTenantsGetItem'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function xXDeprecatedApiTenantsGetItemAsyncWithHttpInfo($uuid, string $contentType = self::contentTypes['xXDeprecatedApiTenantsGetItem'][0])
    {
        $returnType = '\OpenAPI\Client\Model\TenantTenantRead';
        $request = $this->xXDeprecatedApiTenantsGetItemRequest($uuid, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'xXDeprecatedApiTenantsGetItem'
     *
     * @param  string $uuid Tenant identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['xXDeprecatedApiTenantsGetItem'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     * @deprecated
     */
    public function xXDeprecatedApiTenantsGetItemRequest($uuid, string $contentType = self::contentTypes['xXDeprecatedApiTenantsGetItem'][0])
    {

        // verify the required parameter 'uuid' is set
        if ($uuid === null || (is_array($uuid) && count($uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uuid when calling xXDeprecatedApiTenantsGetItem'
            );
        }


        $resourcePath = '/instance/tenants/{uuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'uuid' . '}',
                ObjectSerializer::toPathValue($uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/ld+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-AUTH-TOKEN');
        if ($apiKey !== null) {
            $headers['X-AUTH-TOKEN'] = $apiKey;
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation xXDeprecatedApiTenantsPutItem
     *
     * Replaces the Tenant resource.
     *
     * @param  string $uuid Tenant identifier (required)
     * @param  \OpenAPI\Client\Model\TenantTenantWrite $tenant_tenant_write The updated Tenant resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['xXDeprecatedApiTenantsPutItem'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\TenantTenantRead
     * @deprecated
     */
    public function xXDeprecatedApiTenantsPutItem($uuid, $tenant_tenant_write, string $contentType = self::contentTypes['xXDeprecatedApiTenantsPutItem'][0])
    {
        list($response) = $this->xXDeprecatedApiTenantsPutItemWithHttpInfo($uuid, $tenant_tenant_write, $contentType);
        return $response;
    }

    /**
     * Operation xXDeprecatedApiTenantsPutItemWithHttpInfo
     *
     * Replaces the Tenant resource.
     *
     * @param  string $uuid Tenant identifier (required)
     * @param  \OpenAPI\Client\Model\TenantTenantWrite $tenant_tenant_write The updated Tenant resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['xXDeprecatedApiTenantsPutItem'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\TenantTenantRead, HTTP status code, HTTP response headers (array of strings)
     * @deprecated
     */
    public function xXDeprecatedApiTenantsPutItemWithHttpInfo($uuid, $tenant_tenant_write, string $contentType = self::contentTypes['xXDeprecatedApiTenantsPutItem'][0])
    {
        $request = $this->xXDeprecatedApiTenantsPutItemRequest($uuid, $tenant_tenant_write, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\TenantTenantRead' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\TenantTenantRead' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\TenantTenantRead', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\TenantTenantRead';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\TenantTenantRead',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation xXDeprecatedApiTenantsPutItemAsync
     *
     * Replaces the Tenant resource.
     *
     * @param  string $uuid Tenant identifier (required)
     * @param  \OpenAPI\Client\Model\TenantTenantWrite $tenant_tenant_write The updated Tenant resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['xXDeprecatedApiTenantsPutItem'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function xXDeprecatedApiTenantsPutItemAsync($uuid, $tenant_tenant_write, string $contentType = self::contentTypes['xXDeprecatedApiTenantsPutItem'][0])
    {
        return $this->xXDeprecatedApiTenantsPutItemAsyncWithHttpInfo($uuid, $tenant_tenant_write, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation xXDeprecatedApiTenantsPutItemAsyncWithHttpInfo
     *
     * Replaces the Tenant resource.
     *
     * @param  string $uuid Tenant identifier (required)
     * @param  \OpenAPI\Client\Model\TenantTenantWrite $tenant_tenant_write The updated Tenant resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['xXDeprecatedApiTenantsPutItem'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function xXDeprecatedApiTenantsPutItemAsyncWithHttpInfo($uuid, $tenant_tenant_write, string $contentType = self::contentTypes['xXDeprecatedApiTenantsPutItem'][0])
    {
        $returnType = '\OpenAPI\Client\Model\TenantTenantRead';
        $request = $this->xXDeprecatedApiTenantsPutItemRequest($uuid, $tenant_tenant_write, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'xXDeprecatedApiTenantsPutItem'
     *
     * @param  string $uuid Tenant identifier (required)
     * @param  \OpenAPI\Client\Model\TenantTenantWrite $tenant_tenant_write The updated Tenant resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['xXDeprecatedApiTenantsPutItem'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     * @deprecated
     */
    public function xXDeprecatedApiTenantsPutItemRequest($uuid, $tenant_tenant_write, string $contentType = self::contentTypes['xXDeprecatedApiTenantsPutItem'][0])
    {

        // verify the required parameter 'uuid' is set
        if ($uuid === null || (is_array($uuid) && count($uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uuid when calling xXDeprecatedApiTenantsPutItem'
            );
        }

        // verify the required parameter 'tenant_tenant_write' is set
        if ($tenant_tenant_write === null || (is_array($tenant_tenant_write) && count($tenant_tenant_write) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant_tenant_write when calling xXDeprecatedApiTenantsPutItem'
            );
        }


        $resourcePath = '/instance/tenants/{uuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'uuid' . '}',
                ObjectSerializer::toPathValue($uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/ld+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($tenant_tenant_write)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($tenant_tenant_write));
            } else {
                $httpBody = $tenant_tenant_write;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-AUTH-TOKEN');
        if ($apiKey !== null) {
            $headers['X-AUTH-TOKEN'] = $apiKey;
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
