<?php
/**
 * AvailableDaysApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Probatix API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AvailableDaysApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AvailableDaysApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiCheckoutAvailableDays
     *
     * Retrieves the collection of AvailableDays resources..
     *
     */
    public function testApiCheckoutAvailableDays()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for xXDeprecatedApiCheckoutAvailableDays
     *
     * Retrieves the collection of AvailableDays resources..
     *
     */
    public function testXXDeprecatedApiCheckoutAvailableDays()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for xXDeprecatedApiCheckoutAvailableDaysDe
     *
     * Retrieves the collection of AvailableDays resources..
     *
     */
    public function testXXDeprecatedApiCheckoutAvailableDaysDe()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for xXDeprecatedApiCheckoutAvailableDaysEn
     *
     * Retrieves the collection of AvailableDays resources..
     *
     */
    public function testXXDeprecatedApiCheckoutAvailableDaysEn()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for xXDeprecatedApiCheckoutAvailableDaysFr
     *
     * Retrieves the collection of AvailableDays resources..
     *
     */
    public function testXXDeprecatedApiCheckoutAvailableDaysFr()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for xXDeprecatedApiCheckoutAvailableDaysRu
     *
     * Retrieves the collection of AvailableDays resources..
     *
     */
    public function testXXDeprecatedApiCheckoutAvailableDaysRu()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for xXDeprecatedApiCheckoutAvailableDaysUk
     *
     * Retrieves the collection of AvailableDays resources..
     *
     */
    public function testXXDeprecatedApiCheckoutAvailableDaysUk()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for xXDeprecatedApiCheckoutAvailableDaysZh
     *
     * Retrieves the collection of AvailableDays resources..
     *
     */
    public function testXXDeprecatedApiCheckoutAvailableDaysZh()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
