<?php
/**
 * InternalApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Probatix API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * InternalApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InternalApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiApiInternalcustomPrintingWorkflowsGetCollection
     *
     * Retrieves the collection of CustomPrintingWorkflow resources..
     *
     */
    public function testApiApiInternalcustomPrintingWorkflowsGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalcustomPrintingWorkflowsPost
     *
     * Creates a CustomPrintingWorkflow resource..
     *
     */
    public function testApiApiInternalcustomPrintingWorkflowsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalcustomPrintingWorkflowsUuidGet
     *
     * Retrieves a CustomPrintingWorkflow resource..
     *
     */
    public function testApiApiInternalcustomPrintingWorkflowsUuidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalcustomPrintingWorkflowsUuidPatch
     *
     * Updates the CustomPrintingWorkflow resource..
     *
     */
    public function testApiApiInternalcustomPrintingWorkflowsUuidPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalcustomersGetCollection
     *
     * Retrieves the collection of Customer resources..
     *
     */
    public function testApiApiInternalcustomersGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalcustomersPost
     *
     * Creates a Customer resource..
     *
     */
    public function testApiApiInternalcustomersPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalcustomersUuidGet
     *
     * Retrieves a Customer resource..
     *
     */
    public function testApiApiInternalcustomersUuidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalcustomersUuidPatch
     *
     * Updates the Customer resource..
     *
     */
    public function testApiApiInternalcustomersUuidPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternaldocumentsGetCollection
     *
     * Retrieves the collection of Document resources..
     *
     */
    public function testApiApiInternaldocumentsGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternaldocumentsPost
     *
     * Creates a Document resource..
     *
     */
    public function testApiApiInternaldocumentsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternaldocumentsUuidGet
     *
     * Retrieves a Document resource..
     *
     */
    public function testApiApiInternaldocumentsUuidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternaldocumentsUuidPatch
     *
     * Updates the Document resource..
     *
     */
    public function testApiApiInternaldocumentsUuidPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternallocationsGetCollection
     *
     * Retrieves the collection of Location resources..
     *
     */
    public function testApiApiInternallocationsGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternallocationsPost
     *
     * Creates a Location resource..
     *
     */
    public function testApiApiInternallocationsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternallocationsUuidGet
     *
     * Retrieves a Location resource..
     *
     */
    public function testApiApiInternallocationsUuidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternallocationsUuidPatch
     *
     * Updates the Location resource..
     *
     */
    public function testApiApiInternallocationsUuidPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalorderProductsGetCollection
     *
     * Retrieves the collection of OrderProduct resources..
     *
     */
    public function testApiApiInternalorderProductsGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalorderProductsPost
     *
     * Creates a OrderProduct resource..
     *
     */
    public function testApiApiInternalorderProductsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalorderProductsUuidGet
     *
     * Retrieves a OrderProduct resource..
     *
     */
    public function testApiApiInternalorderProductsUuidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalorderProductsUuidPatch
     *
     * Updates the OrderProduct resource..
     *
     */
    public function testApiApiInternalorderProductsUuidPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalorderVouchersGetCollection
     *
     * Retrieves the collection of OrderVoucher resources..
     *
     */
    public function testApiApiInternalorderVouchersGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalorderVouchersPost
     *
     * Creates a OrderVoucher resource..
     *
     */
    public function testApiApiInternalorderVouchersPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalorderVouchersUuidGet
     *
     * Retrieves a OrderVoucher resource..
     *
     */
    public function testApiApiInternalorderVouchersUuidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalorderVouchersUuidPatch
     *
     * Updates the OrderVoucher resource..
     *
     */
    public function testApiApiInternalorderVouchersUuidPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalordersGetCollection
     *
     * Retrieves the collection of Order resources..
     *
     */
    public function testApiApiInternalordersGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalordersPost
     *
     * Creates a Order resource..
     *
     */
    public function testApiApiInternalordersPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalordersUuidGet
     *
     * Retrieves a Order resource..
     *
     */
    public function testApiApiInternalordersUuidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalordersUuidPatch
     *
     * Updates the Order resource..
     *
     */
    public function testApiApiInternalordersUuidPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalpatientEventsGetCollection
     *
     * Retrieves the collection of PatientEvent resources..
     *
     */
    public function testApiApiInternalpatientEventsGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalpatientEventsPost
     *
     * Creates a PatientEvent resource..
     *
     */
    public function testApiApiInternalpatientEventsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalpatientEventsUuidGet
     *
     * Retrieves a PatientEvent resource..
     *
     */
    public function testApiApiInternalpatientEventsUuidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalpatientEventsUuidPatch
     *
     * Updates the PatientEvent resource..
     *
     */
    public function testApiApiInternalpatientEventsUuidPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalpatientsGetCollection
     *
     * Retrieves the collection of Patient resources..
     *
     */
    public function testApiApiInternalpatientsGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalpatientsPost
     *
     * Creates a Patient resource..
     *
     */
    public function testApiApiInternalpatientsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalpatientsUuidGet
     *
     * Retrieves a Patient resource..
     *
     */
    public function testApiApiInternalpatientsUuidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalpatientsUuidPatch
     *
     * Updates the Patient resource..
     *
     */
    public function testApiApiInternalpatientsUuidPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalprobeIdentifiersGetCollection
     *
     * Retrieves the collection of ProbeIdentifier resources..
     *
     */
    public function testApiApiInternalprobeIdentifiersGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalprobeIdentifiersIdGet
     *
     * Retrieves a ProbeIdentifier resource..
     *
     */
    public function testApiApiInternalprobeIdentifiersIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalprobeIdentifiersIdPatch
     *
     * Updates the ProbeIdentifier resource..
     *
     */
    public function testApiApiInternalprobeIdentifiersIdPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalprobeIdentifiersPost
     *
     * Creates a ProbeIdentifier resource..
     *
     */
    public function testApiApiInternalprobeIdentifiersPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalproductsGetCollection
     *
     * Retrieves the collection of Product resources..
     *
     */
    public function testApiApiInternalproductsGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalproductsPost
     *
     * Creates a Product resource..
     *
     */
    public function testApiApiInternalproductsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalproductsUuidGet
     *
     * Retrieves a Product resource..
     *
     */
    public function testApiApiInternalproductsUuidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalproductsUuidPatch
     *
     * Updates the Product resource..
     *
     */
    public function testApiApiInternalproductsUuidPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternaltenantsGetCollection
     *
     * Retrieves the collection of Tenant resources..
     *
     */
    public function testApiApiInternaltenantsGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternaltenantsPost
     *
     * Creates a Tenant resource..
     *
     */
    public function testApiApiInternaltenantsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternaltenantsUuidGet
     *
     * Retrieves a Tenant resource..
     *
     */
    public function testApiApiInternaltenantsUuidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternaltenantsUuidPatch
     *
     * Updates the Tenant resource..
     *
     */
    public function testApiApiInternaltenantsUuidPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalusersGetCollection
     *
     * Retrieves the collection of User resources..
     *
     */
    public function testApiApiInternalusersGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalusersPost
     *
     * Creates a User resource..
     *
     */
    public function testApiApiInternalusersPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalusersUuidGet
     *
     * Retrieves a User resource..
     *
     */
    public function testApiApiInternalusersUuidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalusersUuidPatch
     *
     * Updates the User resource..
     *
     */
    public function testApiApiInternalusersUuidPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalvouchersGetCollection
     *
     * Retrieves the collection of Voucher resources..
     *
     */
    public function testApiApiInternalvouchersGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalvouchersPost
     *
     * Creates a Voucher resource..
     *
     */
    public function testApiApiInternalvouchersPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalvouchersUuidGet
     *
     * Retrieves a Voucher resource..
     *
     */
    public function testApiApiInternalvouchersUuidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApiInternalvouchersUuidPatch
     *
     * Updates the Voucher resource..
     *
     */
    public function testApiApiInternalvouchersUuidPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
