<?php
/**
 * OrderApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Probatix API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OrderApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiOrdersCheckoutCancelBookingItem
     *
     * Cancel Order..
     *
     */
    public function testApiOrdersCheckoutCancelBookingItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrdersCheckoutCheckVoucherCollection
     *
     * Check Voucher..
     *
     */
    public function testApiOrdersCheckoutCheckVoucherCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrdersCheckoutGetStatusItem
     *
     * Get Order status..
     *
     */
    public function testApiOrdersCheckoutGetStatusItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrdersCheckoutPlaceOrderCollection
     *
     * Place Order..
     *
     */
    public function testApiOrdersCheckoutPlaceOrderCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrdersDeleteXXDeprecatedCheckoutCancelBookingItemDe
     *
     * DEPRECATED - Cancel Order..
     *
     */
    public function testApiOrdersDeleteXXDeprecatedCheckoutCancelBookingItemDe()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrdersGetXXDeprecatedCheckoutGetStatusItem
     *
     * DEPRECATED - Get Order status..
     *
     */
    public function testApiOrdersGetXXDeprecatedCheckoutGetStatusItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrdersPostXXDeprecatedCheckoutCheckVoucherDe
     *
     * DEPRECATED - Check Voucher..
     *
     */
    public function testApiOrdersPostXXDeprecatedCheckoutCheckVoucherDe()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrdersPostXXDeprecatedCheckoutCheckVoucherEn
     *
     * DEPRECATED - Check Voucher..
     *
     */
    public function testApiOrdersPostXXDeprecatedCheckoutCheckVoucherEn()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrdersPostXXDeprecatedCheckoutCheckVoucherFr
     *
     * DEPRECATED - Check Voucher..
     *
     */
    public function testApiOrdersPostXXDeprecatedCheckoutCheckVoucherFr()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrdersPostXXDeprecatedCheckoutCheckVoucherRu
     *
     * DEPRECATED - Check Voucher..
     *
     */
    public function testApiOrdersPostXXDeprecatedCheckoutCheckVoucherRu()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrdersPostXXDeprecatedCheckoutCheckVoucherUk
     *
     * DEPRECATED - Check Voucher..
     *
     */
    public function testApiOrdersPostXXDeprecatedCheckoutCheckVoucherUk()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrdersPostXXDeprecatedCheckoutCheckVoucherZh
     *
     * DEPRECATED - Check Voucher..
     *
     */
    public function testApiOrdersPostXXDeprecatedCheckoutCheckVoucherZh()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrdersPostXXDeprecatedCheckoutPlaceOrderDe
     *
     * Place Order..
     *
     */
    public function testApiOrdersPostXXDeprecatedCheckoutPlaceOrderDe()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrdersPostXXDeprecatedCheckoutPlaceOrderEn
     *
     * Place Order..
     *
     */
    public function testApiOrdersPostXXDeprecatedCheckoutPlaceOrderEn()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrdersPostXXDeprecatedCheckoutPlaceOrderFr
     *
     * Place Order..
     *
     */
    public function testApiOrdersPostXXDeprecatedCheckoutPlaceOrderFr()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrdersPostXXDeprecatedCheckoutPlaceOrderRu
     *
     * Place Order..
     *
     */
    public function testApiOrdersPostXXDeprecatedCheckoutPlaceOrderRu()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrdersPostXXDeprecatedCheckoutPlaceOrderUk
     *
     * Place Order..
     *
     */
    public function testApiOrdersPostXXDeprecatedCheckoutPlaceOrderUk()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrdersPostXXDeprecatedCheckoutPlaceOrderZh
     *
     * Place Order..
     *
     */
    public function testApiOrdersPostXXDeprecatedCheckoutPlaceOrderZh()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
