<?php
/**
 * ProductApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Probatix API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiProductsGetXXDeprecatedCheckoutProductsDe
     *
     * Retrieves the collection of Product resources..
     *
     */
    public function testApiProductsGetXXDeprecatedCheckoutProductsDe()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiProductsGetXXDeprecatedCheckoutProductsEn
     *
     * Retrieves the collection of Product resources..
     *
     */
    public function testApiProductsGetXXDeprecatedCheckoutProductsEn()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiProductsGetXXDeprecatedCheckoutProductsFr
     *
     * Retrieves the collection of Product resources..
     *
     */
    public function testApiProductsGetXXDeprecatedCheckoutProductsFr()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiProductsGetXXDeprecatedCheckoutProductsRu
     *
     * Retrieves the collection of Product resources..
     *
     */
    public function testApiProductsGetXXDeprecatedCheckoutProductsRu()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiProductsGetXXDeprecatedCheckoutProductsUk
     *
     * Retrieves the collection of Product resources..
     *
     */
    public function testApiProductsGetXXDeprecatedCheckoutProductsUk()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiProductsGetXXDeprecatedCheckoutProductsZh
     *
     * Retrieves the collection of Product resources..
     *
     */
    public function testApiProductsGetXXDeprecatedCheckoutProductsZh()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiProductsProductsCollection
     *
     * Retrieves the collection of Product resources..
     *
     */
    public function testApiProductsProductsCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
